[package]
name = "crdt-buffer"
version = "0.1.0"
edition = "2021"
author = ["Huang Chengjie<597857074@qq.com>"]
description = "A CRDT data buffer decode/encode library."
license = "MIT"
repository = "https://github.com/KaygNas/crdt-buffer"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.88"
